# import pandas as pd
# # import os
# import numpy as np
# # import json
# # from IPython import display
# # import requests
# # from tqdm import tqdm
#
#
# #train_2019 = pd.read_csv('sberbank_data/data_2019/dota2_skill_train.csv')
# # train_vsesib = pd.read_csv('sberbank_data/data/skill_train.csv')
# # abilities = pd.read_csv('sberbank_data/data_2019/dota2_abilities.csv')
# test = pd.read_csv('sberbank_data/data_2019/dota2_skill_test.csv')
# #
# # path_vsesib = 'sberbank_data/data/skill_train.jsonlines'
# # path_2019 = 'sberbank_data/data_2019/dota2_skill_train.jsonlines'
# # path_test = 'sberbank_data/data_2019/dota2_skill_test.jsonlines'
# test.shape
# 43265 * 0.603167
# #26096 - False
#
# def best_pred(pred1, pred2, pred3, y_valid):
#     pred1 = np.array(pred1)
#     pred2 = np.array(pred2)
#     pred3 = np.array(pred3)
#
#     merge = (pred1+pred2+pred3) / 3
#
#     max_acc = -1
#     best_thresh = -1
#     best_pred = []
#
#     for threshold in range(0.1,1,0.03):
#         stacked = merge > threshold
#         if max_acc < accuracy_score(stacked, y_valid):
#             max_acc = accuracy_score(stacked, y_valid)
#             best_thresh = threshold
#             best_pred = stacked
#
#     return print('max_accuracy: '+str(max_acc), 'best_threshold: '+str(best_thresh))
#
# d
#d
#
#
# with open(path_2019) as fin:
#     for line in tqdm(fin):
#         record = json.loads(line)
#         break

targets_names = ['npc_dota_unit_tombstone1',
 'npc_dota_hero_necrolyte',
 'npc_dota_goodguys_tower3_top',
 'npc_dota_hero_rubick',
 'npc_dota_neutral_prowler_shaman',
 'npc_dota_hero_viper',
 'npc_dota_zeus_cloud',
 'npc_dota_phoenix_sun',
 'npc_dota_creep_goodguys_melee_upgraded',
 'npc_dota_neutral_forest_troll_high_priest',
 'npc_dota_hero_oracle',
 'npc_dota_neutral_satyr_soulstealer',
 'npc_dota_hero_brewmaster',
 'npc_dota_shadow_shaman_ward_1',
 'npc_dota_hero_tidehunter',
 'npc_dota_hero_razor',
 'npc_dota_neutral_giant_wolf',
 'npc_dota_neutral_harpy_storm',
 'npc_dota_hero_alchemist',
 'npc_dota_hero_weaver',
 'npc_dota_lone_druid_bear3',
 'npc_dota_hero_enchantress',
 'npc_dota_brewmaster_fire_2',
 'npc_dota_creep_badguys_melee',
 'npc_dota_badguys_tower3_mid',
 'npc_dota_hero_phantom_lancer',
 'npc_dota_hero_puck',
 'npc_dota_neutral_kobold_taskmaster',
 'npc_dota_neutral_forest_troll_berserker',
 'npc_dota_hero_nevermore',
 'npc_dota_hero_dark_willow',
 'npc_dota_hero_dark_seer',
 'npc_dota_neutral_alpha_wolf',
 'npc_dota_hero_bane',
 'npc_dota_creep_badguys_melee_upgraded_mega',
 'npc_dota_hero_elder_titan',
 'npc_dota_goodguys_range_rax_top',
 'npc_dota_pugna_nether_ward_3',
 'npc_dota_goodguys_melee_rax_mid',
 'npc_dota_hero_centaur',
 'npc_dota_hero_treant',
 'npc_dota_hero_furion',
 'npc_dota_unit_tombstone3',
 'npc_dota_hero_shadow_demon',
 'npc_dota_beastmaster_boar_4',
 'npc_dota_goodguys_siege',
 'npc_dota_neutral_mud_golem_split',
 'npc_dota_hero_lina',
 'npc_dota_greater_eidolon',
 'npc_dota_hero_undying',
 'npc_dota_hero_sand_king',
 'npc_dota_beastmaster_hawk_1',
 'npc_dota_hero_jakiro',
 'npc_dota_warlock_golem_3',
 'npc_dota_neutral_rock_golem',
 'npc_dota_goodguys_siege_upgraded_mega',
 'npc_dota_neutral_mud_golem',
 'npc_dota_hero_lich',
 'npc_dota_creep_goodguys_ranged',
 'npc_dota_hero_skeleton_king',
 'npc_dota_hero_silencer',
 'npc_dota_hero_monkey_king',
 'npc_dota_badguys_tower1_bot',
 'npc_dota_neutral_enraged_wildkin',
 'npc_dota_lycan_wolf4',
 'npc_dota_badguys_siege_upgraded',
 'npc_dota_brewmaster_earth_1',
 'npc_dota_badguys_range_rax_top',
 'npc_dota_badguys_melee_rax_mid',
 'npc_dota_hero_medusa',
 'npc_dota_venomancer_plague_ward_4',
 'npc_dota_hero_juggernaut',
 'npc_dota_hero_phoenix',
 'npc_dota_creep_goodguys_melee_upgraded_mega',
 'npc_dota_hero_faceless_void',
 'npc_dota_wraith_king_skeleton_warrior',
 'npc_dota_hero_arc_warden',
 'npc_dota_badguys_tower4',
 'npc_dota_lone_druid_bear4',
 'npc_dota_earth_spirit_stone',
 'npc_dota_furion_treant_1',
 'npc_dota_hero_ursa',
 'npc_dota_hero_pugna',
 'npc_dota_brewmaster_earth_3',
 'npc_dota_hero_wisp',
 'npc_dota_hero_storm_spirit',
 'npc_dota_hero_abyssal_underlord',
 'npc_dota_hero_chaos_knight',
 'npc_dota_hero_huskar',
 'npc_dota_goodguys_tower1_mid',
 'npc_dota_badguys_tower2_top',
 'npc_dota_grimstroke_ink_creature',
 'npc_dota_goodguys_fort',
 'npc_dota_neutral_kobold_tunneler',
 'npc_dota_neutral_harpy_scout',
 'npc_dota_venomancer_plague_ward_2',
 'npc_dota_neutral_fel_beast',
 'npc_dota_hero_zuus',
 'npc_dota_lone_druid_bear2',
 'npc_dota_broodmother_spiderite',
 'npc_dota_hero_night_stalker',
 'npc_dota_pugna_nether_ward_4',
 'npc_dota_beastmaster_hawk_4',
 'npc_dota_hero_clinkz',
 'npc_dota_goodguys_melee_rax_top',
 'npc_dota_beastmaster_boar_3',
 'npc_dota_badguys_tower1_top',
 'npc_dota_badguys_fort',
 'npc_dota_hero_broodmother',
 'npc_dota_hero_witch_doctor',
 'npc_dota_hero_grimstroke',
 'npc_dota_hero_enigma',
 'npc_dota_creep_goodguys_melee',
 'npc_dota_lycan_wolf2',
 'npc_dota_hero_disruptor',
 'npc_dota_necronomicon_archer_3',
 'npc_dota_goodguys_healers',
 'npc_dota_neutral_dark_troll',
 'npc_dota_creep_goodguys_ranged_upgraded',
 'npc_dota_hero_dazzle',
 'npc_dota_eidolon',
 'npc_dota_hero_beastmaster',
 'npc_dota_goodguys_tower3_bot',
 'npc_dota_neutral_ghost',
 'npc_dota_hero_earthshaker',
 'npc_dota_neutral_satyr_hellcaller',
 'npc_dota_hero_lycan',
 'npc_dota_hero_gyrocopter',
 'npc_dota_unit_undying_zombie',
 'npc_dota_weaver_swarm',
 'npc_dota_brewmaster_fire_1',
 'npc_dota_creep_badguys_melee_upgraded',
 'npc_dota_juggernaut_healing_ward',
 'npc_dota_hero_keeper_of_the_light',
 'npc_dota_neutral_ogre_magi',
 'npc_dota_hero_ember_spirit',
 'npc_dota_hero_life_stealer',
 'npc_dota_hero_tinker',
 'npc_dota_hero_terrorblade',
 'npc_dota_hero_morphling',
 'npc_dota_neutral_granite_golem',
 'npc_dota_hero_spectre',
 'npc_dota_neutral_big_thunder_lizard',
 'npc_dota_warlock_golem_scepter_2',
 'npc_dota_lycan_wolf1',
 'npc_dota_venomancer_plague_ward_1',
 'npc_dota_creep_goodguys_ranged_upgraded_mega',
 'npc_dota_ignis_fatuus',
 'npc_dota_neutral_black_drake',
 'npc_dota_goodguys_tower3_mid',
 'npc_dota_hero_antimage',
 'npc_dota_beastmaster_hawk_3',
 'npc_dota_furion_treant_large',
 'npc_dota_furion_treant',
 'npc_dota_hero_invoker',
 'npc_dota_hero_dragon_knight',
 'npc_dota_neutral_ogre_mauler',
 'npc_dota_badguys_range_rax_mid',
 'npc_dota_observer_wards',
 'npc_dota_hero_death_prophet',
 'npc_dota_hero_skywrath_mage',
 'npc_dota_hero_warlock',
 'npc_dota_hero_drow_ranger',
 'npc_dota_hero_rattletrap',
 'npc_dota_hero_phantom_assassin',
 'npc_dota_unit_undying_zombie_torso',
 'npc_dota_gyrocopter_homing_missile',
 'npc_dota_hero_queenofpain',
 'npc_dota_hero_nyx_assassin',
 'npc_dota_techies_remote_mine',
 'npc_dota_hero_abaddon',
 'npc_dota_brewmaster_storm_2',
 'npc_dota_hero_tusk',
 'npc_dota_badguys_tower3_bot',
 'npc_dota_necronomicon_warrior_3',
 'npc_dota_hero_mirana',
 'npc_dota_neutral_polar_furbolg_champion',
 'npc_dota_badguys_tower1_mid',
 'npc_dota_furion_treant_4',
 'npc_dota_hero_leshrac',
 'npc_dota_hero_slark',
 'npc_dota_brewmaster_earth_2',
 'npc_dota_warlock_golem_2',
 'npc_dota_hero_sniper',
 'npc_dota_neutral_gnoll_assassin',
 'npc_dota_invoker_forged_spirit',
 'npc_dota_hero_earth_spirit',
 'npc_dota_neutral_black_dragon',
 'npc_dota_hero_templar_assassin',
 'npc_dota_hero_vengefulspirit',
 'npc_dota_hero_techies',
 'npc_dota_brewmaster_storm_1',
 'npc_dota_techies_stasis_trap',
 'npc_dota_sentry_wards',
 'npc_dota_hero_windrunner',
 'npc_dota_hero_ogre_magi',
 'npc_dota_hero_slardar',
 'npc_dota_hero_ancient_apparition',
 'npc_dota_badguys_tower3_top',
 'npc_dota_hero_riki',
 'npc_dota_goodguys_tower4',
 'npc_dota_hero_visage',
 'npc_dota_hero_winter_wyvern',
 'npc_dota_visage_familiar2',
 'npc_dota_warlock_golem_scepter_3',
 'npc_dota_beastmaster_boar_2',
 'npc_dota_brewmaster_storm_3',
 'npc_dota_roshan',
 'npc_dota_goodguys_melee_rax_bot',
 'npc_dota_hero_kunkka',
 'npc_dota_goodguys_siege_upgraded',
 'npc_dota_badguys_melee_rax_bot',
 'npc_dota_necronomicon_warrior_2',
 'npc_dota_lone_druid_bear1',
 'npc_dota_shadow_shaman_ward_3',
 'npc_dota_hero_doom_bringer',
 'npc_dota_furion_treant_2',
 'npc_dota_lycan_wolf3',
 'npc_dota_hero_bounty_hunter',
 'npc_dota_hero_pudge',
 'npc_dota_goodguys_fillers',
 'npc_dota_neutral_centaur_outrunner',
 'npc_dota_hero_pangolier',
 'npc_dota_neutral_wildkin',
 'npc_dota_goodguys_tower1_bot',
 'npc_dota_goodguys_tower2_top',
 'npc_dota_beastmaster_boar_1',
 'npc_dota_hero_batrider',
 'npc_dota_necronomicon_archer_2',
 'npc_dota_creep_badguys_ranged_upgraded_mega',
 'npc_dota_brewmaster_fire_3',
 'npc_dota_hero_venomancer',
 'npc_dota_hero_luna',
 'npc_dota_hero_shadow_shaman',
 'npc_dota_neutral_dark_troll_warlord',
 'npc_dota_unit_tombstone2',
 'npc_dota_furion_treant_3',
 'npc_dota_hero_bristleback',
 'npc_dota_neutral_satyr_trickster',
 'npc_dota_badguys_tower2_mid',
 'npc_dota_neutral_mud_golem_split_doom',
 'npc_dota_creep_badguys_ranged_upgraded',
 'npc_dota_hero_sven',
 'npc_dota_visage_familiar3',
 'npc_dota_badguys_melee_rax_top',
 'npc_dota_hero_tiny',
 'npc_dota_badguys_healers',
 'npc_dota_broodmother_spiderling',
 'npc_dota_neutral_polar_furbolg_ursa_warrior',
 'npc_dota_dark_troll_warlord_skeleton_warrior',
 'npc_dota_hero_legion_commander',
 'npc_dota_hero_crystal_maiden',
 'npc_dota_hero_lone_druid',
 'npc_dota_hero_lion',
 'npc_dota_badguys_range_rax_bot',
 'npc_dota_beastmaster_hawk_2',
 'npc_dota_goodguys_range_rax_mid',
 'npc_dota_courier',
 'npc_dota_goodguys_tower2_mid',
 'npc_dota_hero_chen',
 'npc_dota_goodguys_tower1_top',
 'npc_dota_neutral_centaur_khan',
 'npc_dota_clinkz_skeleton_archer',
 'npc_dota_dire_eidolon',
 'npc_dota_badguys_fillers',
 'npc_dota_hero_troll_warlord',
 'npc_dota_hero_axe',
 'npc_dota_venomancer_plague_ward_3',
 'npc_dota_hero_shredder',
 'npc_dota_necronomicon_archer_1',
 'npc_dota_templar_assassin_psionic_trap',
 'npc_dota_hero_omniknight',
 'npc_dota_hero_mars',
 'npc_dota_badguys_siege_upgraded_mega',
 'npc_dota_goodguys_tower2_bot',
 'npc_dota_creep_badguys_ranged',
 'npc_dota_goodguys_range_rax_bot',
 'npc_dota_necronomicon_warrior_1',
 'npc_dota_badguys_tower2_bot',
 'npc_dota_shadow_shaman_ward_2',
 'npc_dota_lesser_eidolon',
 'npc_dota_seasonal_snowman',
 'npc_dota_hero_meepo',
 'npc_dota_badguys_siege',
 'npc_dota_neutral_small_thunder_lizard',
 'npc_dota_visage_familiar1',
 'npc_dota_hero_bloodseeker',
 'npc_dota_hero_naga_siren',
 'npc_dota_warlock_golem_scepter_1',
 'npc_dota_hero_magnataur',
 'npc_dota_warlock_golem_1',
 'npc_dota_neutral_kobold',
 'npc_dota_hero_obsidian_destroyer',
 'npc_dota_hero_spirit_breaker',
 'npc_dota_techies_land_mine',
 'npc_dota_pugna_nether_ward_1',
 'npc_dota_neutral_prowler_acolyte',
 'npc_dota_unit_tombstone4',
 'npc_dota_pugna_nether_ward_2']
